version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Mount the backend code for hot-reloading
    env_file:
      - ./backend/.env # Load environment variables